/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.example;

import java.awt.Button;
import java.awt.TextField;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;


/**
 *
 * @author Administrator
 */
public class page1 extends JPanel implements ItemListener {

    private JTabbedPane mJTabbedPane = null;
    private JPanel pan2 = null;
    private page2 cardPanel2 = null;
    private page3 cardPanel1 = null;
    private page4 cardPanel10 = null;
    private MyPanel myPanel = null;
    private MyPanel1 myPanel1 = null;


    public void setJTabbedPane(JTabbedPane mJTabbedPane,JPanel pan2, page2 cardPanel2, page3 cardPanel1, page4 cardPanel10 ,MyPanel myPanel, MyPanel1 myPanel1) {
        this.mJTabbedPane = mJTabbedPane;
        this.pan2 = pan2;
        this.cardPanel2 = cardPanel2;
        this.cardPanel1 = cardPanel1;
        this.cardPanel10 = cardPanel10;
        this.myPanel = myPanel;
        this.myPanel1 = myPanel1;
    }

    public void setSelectedComponent() {
        mJTabbedPane.setSelectedComponent(pan2);
        cardPanel2.setVisible(true);
        cardPanel1.setVisible(true);
        cardPanel10.setVisible(true);
        myPanel.setVisible(true);
        myPanel1.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    public page1() {
        initComponents();
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new JLabel();
        jPanel1 = new JPanel();
        jLabel3 = new JLabel();
        jLabel2 = new JLabel();
        jLabel4 = new JLabel();
        jTextField1 = new TextField();
        jTextField2 = new TextField();

        Handle0 handle = new Handle0(page1.this);
        jTextField1.addActionListener(handle);
        jTextField2.addActionListener(handle);

        jTextField1.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                int keyChar = e.getKeyChar();
                if (keyChar >= KeyEvent.VK_0 && keyChar <= KeyEvent.VK_9
                        || keyChar == KeyEvent.VK_PERIOD) {

                } else {
                    e.consume(); // 关键，屏蔽掉非法输入
                }
            }
        });


        jTextField2.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                int keyChar = e.getKeyChar();
                if (keyChar >= KeyEvent.VK_0 && keyChar <= KeyEvent.VK_9
                        || keyChar == KeyEvent.VK_PERIOD) {

                } else {
                    e.consume(); // 关键，屏蔽掉非法输入
                }
            }
        });

        jTextField2.setEchoChar('*');

        button1 = new Button();
        button1.addActionListener(handle);

        jLabel1.setIcon(new ImageIcon("Mixed", "33.jpg")); // NOI18N
        jLabel1.setText("");

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 1262, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel3.setText("版权：合肥美菱股份有限公司研究院  编制：李二鹏");

        jLabel2.setText("账号：");

        jLabel4.setText("密码：");

        button1.setLabel("登录");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 20, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(472, 472, 472))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(396, 396, 396)
                                .addComponent(jLabel3)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(jLabel2)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>                          

    // Variables declaration - do not modify                     
    private Button button1;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JPanel jPanel1;
    TextField jTextField1;
    TextField jTextField2;
    // End of variables declaration                   


    @Override
    public void itemStateChanged(ItemEvent arg0) {
        // TODO Auto-generated method stub

    }



    class Handle0 implements ActionListener // ①实现某接口
    {
        protected page1 newjframe;

        public Handle0(page1 newjframe) // 构造函数
        {
            this.newjframe = newjframe;
        }

        public void actionPerformed(ActionEvent e) // ②实现该接口中的所有方法
        {
            if (e.getActionCommand().equals("登录"))// 是Red按钮事件
            {
                double h1 = Double.valueOf(newjframe.jTextField1.getText());
                double h2 = Double.valueOf(newjframe.jTextField2.getText());
                if(h1==1 && h2 ==2)
                {
                    setSelectedComponent();
                }

            }
        }



    }

}
